const description = {
    case: [
        'Space Gray Aluminum Case',
        'Silver Aluminum Case with Space',
        'Gold Aluminum Case with Space',
        'Blue Aluminum Case with Space',
        '(PRODUCT)RED Aluminum Case',
        'Graphite Stainless Steel Case',
        'Silver Stainless Steel Case',
        'Gold Stainless Steel Case',
        'Space Black Titanium Case',
        'Titanium Case',
    ],
    band: [
        'Pistachio Solo Loop',
        'Cantaloupe Solo Loop',
        'Tomales Blue Solo Loop',
        'Deep Navy Solo Loop',
        'Kumquat Solo Loop',
        'Ginger Solo Loop',
        'Pink Citrus Solo Loop',
        'White Solo Loop',
        'Black Solo Loop',
        '(PRODUCT)RED Solo Loop',
        'Electric Orange Braided Solo Loop',
        'Pistachio Braided Solo Loop',
        'Inverness Green Braided Solo Loop',
        'Charcoal Braided Solo Loop',
        'Pride Edition Braided Solo Loop',
        'Pink Punch Braided Solo Loop',
        'Atlantic Blue Braided Solo Loop',
        '(PRODUCT)RED Braided Solo Loop',
        'Cantaloupe Sport Band',
        'Capri Blue Sport Band',
        'Mallard Green Sport Band',
        'Deep Navy Sport Band',
        'Cyprus Green Sport Band',
        'Grapefruit Sport Band',
        'Pink Sand Sport Band',
        'White Sport Band',
        'Black Sport Band',
        '(PRODUCT)RED Sport Band',
        'Black Unity Sport Band',
        'Sunflower Sport Loop',
        'Sea Salt Sport Loop',
        'Abyss Sport Loop',
        'Olive Sport Loop',
        'Plum Sport Loop',
        'Deep Navy Sport Loop',
        'Charcoal Sport Loop',
        'Neon Lime Sport Loop',
        'Surf Blue Sport Loop',
        '(PRODUCT)RED Sport Loop',
        'Pink Citrus Modern Buckle',
        'Garnet Modern Buckle',
        'Scarlet Modern Buckle',
        'Saddle Brown Modern Buckle',
        'Chalk Leather Link',
        'Baltic Blue Leather Link',
        'California Poppy Leather Link',
        'Saddle Brown Leather Link',
        'Black Leather Link',
        'Graphite Milanese Loop',
        'Silver Milanese Loop',
        'Gold Milanese Loop',
        'Silver Link Bracelet',
        'Space Black Link Bracelet',
    ]
}